name: Deploy to Cloud

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            git config --global --add safe.directory /var/www/famiverse
            cd /var/www/famiverse
            git pull
            cd /var/www/famiverse/frontend
            npm install
            npm run build
            pm2 restart famiverse || pm2 start npm --name famiverse -- run start
            cd /var/www/famiverse/api
            npm install
            npm run build
